# Generated by Django 3.1.7 on 2021-03-26 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManagementsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_services', models.CharField(choices=[('LINEスタンプ', 'LINEスタンプ'), ('LINE絵文字', 'LINE絵文字'), ('イラスト', 'イラスト'), ('アイコン', 'アイコン'), ('キャラクター', 'キャラクター'), ('名刺', '名刺'), ('その他', 'その他')], max_length=100)),
                ('ordered_services_memo', models.TextField(blank=True, max_length=1000, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('ordered_media', models.CharField(choices=[('ホームページ', 'ホームページ'), ('ココナラ', 'ココナラ'), ('SNS', 'SNS'), ('直接', '直接'), ('その他', 'その他')], max_length=100)),
                ('personal_or_corporate', models.CharField(choices=[('個人', '個人'), ('法人', '法人')], max_length=50)),
                ('option', models.TextField(blank=True, max_length=500, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('order_price', models.IntegerField(blank=True, default=0, null=True)),
                ('sales_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('create_user', models.CharField(default='', max_length=50)),
                ('review_count', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
